language: objective-c
osx_image: xcode7.3
env:
  global:
  - IOS_SDK="iphonesimulator9.3"
  - BUILD_SCHEME="GoTheFToSleep"
  - TESTS_SCHEME="GoTheFToSleepTests"
  - UI_TESTS_SCHEME="GoTheFToSleepUITests"
  matrix:
    - DESTINATION="OS=8.1,name=iPad 2"          SCHEME="$BUILD_SCHEME"        SDK="$IOS_SDK"     ACTION="build"
    - DESTINATION="OS=8.2,name=iPad 2"          SCHEME="$BUILD_SCHEME"        SDK="$IOS_SDK"     ACTION="build"
    - DESTINATION="OS=8.3,name=iPad 2"          SCHEME="$BUILD_SCHEME"        SDK="$IOS_SDK"     ACTION="build"
    - DESTINATION="OS=8.4,name=iPad 2"          SCHEME="$BUILD_SCHEME"        SDK="$IOS_SDK"     ACTION="build"
    - DESTINATION="OS=9.0,name=iPad 2"          SCHEME="$BUILD_SCHEME"        SDK="$IOS_SDK"     ACTION="build"
    - DESTINATION="OS=9.1,name=iPad 2"          SCHEME="$BUILD_SCHEME"        SDK="$IOS_SDK"     ACTION="build"
    - DESTINATION="OS=9.2,name=iPad 2"          SCHEME="$TESTS_SCHEME"        SDK="$IOS_SDK"     ACTION="test"
    - DESTINATION="OS=9.2,name=iPad 2"          SCHEME="$UI_TESTS_SCHEME"     SDK="$IOS_SDK"     ACTION="test"

script:
  - set -o pipefail
  - xcodebuild -project GoTheFToSleep.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug "$ACTION" | xcpretty -c;