language: objective-c
osx_image: xcode7.3
env:
  global:
  - IOS_SDK=iphonesimulator9.3
  - TESTS_SCHEME="GoTheFToSleepTests"
  matrix:
    - DESTINATION="arch=x86_64"                    SCHEME="$TESTS_SCHEME"             SDK="$OSX_SDK"     RUN_TESTS="YES"
script:
  - set -o pipefail

  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project GoTheFToSleep.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test | xcpretty -c;
    else
      xcodebuild -project GoTheFToSleep.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug build | xcpretty -c;
    fi